services:
  proxy:
    image: traefik:v2.8
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - .traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock

  apache:
    image: httpd
    labels:
      - traefik.enable=true
      - traefik.http.routers.apache.rule=Host(`apache.localhost`)

  nginx:
    image: nginx
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`nginx.localhost`) || Host(`localhost`)

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
      
  grafana:
    image: grafana/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`dashboard.localhost`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
